actor_bc_coef: 0.003
actor_learning_rate: 0.0003
actor_ln: false
actor_n_hiddens: 3
batch_size: 256
critic_bc_coef: 0.0
critic_learning_rate: 0.00005
critic_ln: false
critic_fn: true
critic_n_hiddens: 3
dataset_name: antmaze-medium-play-v2
eval_episodes: 100
eval_every: 50
eval_seed: 42
gamma: 0.999
group: rebrac-antmaze-medium-play-v2
hidden_dim: 256
name: rebrac
noise_clip: 0.5
normalize_q: true
normalize_reward: true
normalize_states: false
num_epochs: 1000
num_updates_on_epoch: 1000
policy_freq: 2
policy_noise: 0.2
project: ReBRAC
tau: 0.005
train_seed: 0
